"""Initial migration - create all tables

Revision ID: 001
Revises: 
Create Date: 2025-08-30 15:19:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create subjects table
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('start_module', sa.Integer(), nullable=True),
    sa.Column('end_module', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year', name='unique_subject')
    )
    
    # Create users table
    op.create_table('users',
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False, server_default='Europe/Moscow'),
    sa.PrimaryKeyConstraint('tg_user_id')
    )
    
    # Create deadlines table
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('hw_name', sa.Text(), nullable=True),
    sa.Column('source_link', sa.Text(), nullable=True),
    sa.Column('soft_deadline_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hard_deadline_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sheet_row_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_row_id')
    )
    op.create_index('idx_deadlines_subject_id', 'deadlines', ['subject_id'], unique=False)
    
    # Create subscriptions table
    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )
    op.create_index('idx_subscriptions_subject_id', 'subscriptions', ['subject_id'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    
    # Create user_notifications table
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('offset_value', sa.Integer(), nullable=False),
    sa.Column('offset_unit', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('offset_value >= 0', name='check_offset_positive'),
    sa.CheckConstraint("offset_unit IN ('days', 'hours', 'minutes')", name='check_offset_unit_valid'),
    sa.CheckConstraint('notification_number IN (1, 2)', name='check_notification_number_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_number', name='unique_user_notification_number')
    )
    
    # Create notification_log table
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('deadline_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadlines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'deadline_id', 'notification_type', name='unique_notification_task')
    )
    op.create_index('idx_notification_log_status_scheduled', 'notification_log', ['status', 'scheduled_for'], unique=False)
    op.create_index('idx_notification_log_user_id', 'notification_log', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_log_user_id', table_name='notification_log')
    op.drop_index('idx_notification_log_status_scheduled', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_table('user_notifications')
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_subject_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_deadlines_subject_id', table_name='deadlines')
    op.drop_table('deadlines')
    op.drop_table('users')
    op.drop_table('subjects')
    # ### end Alembic commands ###