"""Add scheduled notifications and update user settings

Revision ID: 002
Revises: 001
Create Date: 2025-01-09 12:00:00.000000

"""
import contextlib
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | Sequence[str] | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add settings_version column to users table
    op.add_column(
        "users",
        sa.Column("settings_version", sa.Integer(), nullable=True, server_default="1"),
    )

    # Add indexes to deadlines table
    op.create_index(
        "idx_deadlines_soft_ts", "deadlines", ["soft_deadline_ts"], unique=False
    )
    op.create_index(
        "idx_deadlines_hard_ts", "deadlines", ["hard_deadline_ts"], unique=False
    )

    # Create user_notification_settings table
    op.create_table(
        "user_notification_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("reminder1_offset", sa.Integer(), nullable=False, server_default="7"),
        sa.Column("reminder1_unit", sa.Text(), nullable=False, server_default="days"),
        sa.Column("reminder2_offset", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("reminder2_unit", sa.Text(), nullable=False, server_default="days"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint("reminder1_offset >= 0", name="check_reminder1_positive"),
        sa.CheckConstraint("reminder2_offset >= 0", name="check_reminder2_positive"),
        sa.CheckConstraint(
            "reminder1_unit IN ('days', 'hours')", name="check_reminder1_unit_valid"
        ),
        sa.CheckConstraint(
            "reminder2_unit IN ('days', 'hours')", name="check_reminder2_unit_valid"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.tg_user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="unique_user_settings"),
    )

    # Create scheduled_notifications table
    op.create_table(
        "scheduled_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("deadline_id", sa.Integer(), nullable=False),
        sa.Column("deadline_type", sa.Text(), nullable=False),
        sa.Column("notification_number", sa.Integer(), nullable=False),
        sa.Column("original_deadline_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_delivery_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default="scheduled"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'sent', 'cancelled', 'failed')",
            name="check_status_valid",
        ),
        sa.CheckConstraint(
            "notification_number IN (1, 2)", name="check_notif_number_valid"
        ),
        sa.CheckConstraint(
            "deadline_type IN ('soft', 'hard')", name="check_deadline_type_valid"
        ),
        sa.ForeignKeyConstraint(["deadline_id"], ["deadlines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.tg_user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "deadline_id",
            "deadline_type",
            "notification_number",
            name="unique_user_deadline_notification",
        ),
    )

    # Create indexes for scheduled_notifications
    op.create_index(
        "idx_sched_notif_status_time",
        "scheduled_notifications",
        ["status", "planned_delivery_time"],
        unique=False,
    )
    op.create_index(
        "idx_sched_notif_user_status",
        "scheduled_notifications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_sched_notif_deadline",
        "scheduled_notifications",
        ["deadline_id"],
        unique=False,
    )
    op.create_index(
        "idx_sched_notif_delivery_time",
        "scheduled_notifications",
        ["planned_delivery_time"],
        unique=False,
    )

    # Migrate existing user notification settings
    # Create default settings for all existing users
    op.execute("""
        INSERT INTO user_notification_settings (user_id, reminder1_offset, reminder1_unit, reminder2_offset, reminder2_unit, is_active)
        SELECT tg_user_id, 7, 'days', 1, 'days', true
        FROM users
        WHERE tg_user_id NOT IN (SELECT user_id FROM user_notification_settings)
    """)

    with contextlib.suppress(Exception):
        op.add_column("chat_groups", sa.Column("topic_title", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop scheduled_notifications indexes
    op.drop_index("idx_sched_notif_delivery_time", table_name="scheduled_notifications")
    op.drop_index("idx_sched_notif_deadline", table_name="scheduled_notifications")
    op.drop_index("idx_sched_notif_user_status", table_name="scheduled_notifications")
    op.drop_index("idx_sched_notif_status_time", table_name="scheduled_notifications")

    # Drop tables
    op.drop_table("scheduled_notifications")
    op.drop_table("user_notification_settings")

    # Drop deadline indexes
    op.drop_index("idx_deadlines_hard_ts", table_name="deadlines")
    op.drop_index("idx_deadlines_soft_ts", table_name="deadlines")

    # Remove settings_version column from users
    op.drop_column("users", "settings_version")

    with contextlib.suppress(Exception):
        op.drop_column("chat_groups", "topic_title")

    # ### end Alembic commands ###
