"""add_is_active_to_users

Revision ID: 73b82a745d6e
Revises: d6117a9653ff
Create Date: 2025-10-27 19:08:14.211041

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "73b82a745d6e"
down_revision: str | Sequence[str] | None = "d6117a9653ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку с дефолтным значением
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"))

    # Обновляем все существующие записи
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")

    # Теперь делаем колонку NOT NULL
    op.alter_column("users", "is_active", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
