"""Add notification settings: sleep time and update notifications toggle

Revision ID: add_notification_updates
Revises: cbea2120eaa8
Create Date: 2025-01-28 12:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "add_notification_updates"
down_revision: str | Sequence[str] | None = "cbea2120eaa8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add enable_deadline_update_notifications column with default True
    op.add_column(
        "user_notification_settings",
        sa.Column("enable_deadline_update_notifications", sa.Boolean(), nullable=True, server_default="true"),
    )
    
    # Update all existing records to have True for enable_deadline_update_notifications
    op.execute("UPDATE user_notification_settings SET enable_deadline_update_notifications = true WHERE enable_deadline_update_notifications IS NULL")
    
    # Make the column NOT NULL
    op.alter_column("user_notification_settings", "enable_deadline_update_notifications", nullable=False)
    
    # Add sleep time columns (nullable)
    op.add_column(
        "user_notification_settings",
        sa.Column("sleep_start_time", sa.Time(), nullable=True),
    )
    op.add_column(
        "user_notification_settings",
        sa.Column("sleep_end_time", sa.Time(), nullable=True),
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_notification_settings", "sleep_end_time")
    op.drop_column("user_notification_settings", "sleep_start_time")
    op.drop_column("user_notification_settings", "enable_deadline_update_notifications")
    # ### end Alembic commands ###

