ALL_SUBJECTS = [
    # 1 курс
    {"name": "Годовой проект", "year": 1, "start_module": 1, "end_module": 4},
    {"name": "Python для анализа данных", "year": 1, "start_module": 1, "end_module": 1},
    {"name": "SQL", "year": 1, "start_module": 1, "end_module": 1},
    {"name": "Инструменты разработки", "year": 1, "start_module": 1, "end_module": 2},
    {"name": "Математика для анализа данных", "year": 1, "start_module": 1, "end_module": 2},
    {"name": "Анализ временных рядов", "year": 1, "start_module": 2, "end_module": 3},
    {"name": "Машинное обучение (ML)", "year": 1, "start_module": 2, "end_module": 3},
    {"name": "Прикладной Python", "year": 1, "start_module": 2, "end_module": 3},
    {"name": "Промышленная разработка", "year": 1, "start_module": 3, "end_module": 4},
    {"name": "Прикладная статистика для анализа данных", "year": 1, "start_module": 3, "end_module": 4},
    {"name": "Рекомендательные Системы", "year": 1, "start_module": 3, "end_module": 4},
    {"name": "Алгоритмы и Структуры Данных", "year": 1, "start_module": 4, "end_module": 4},
    {"name": "Глубинное обучение", "year": 1, "start_module": 4, "end_module": 4},
    
    # 2 курс
    {"name": "ВКР", "year": 2, "start_module": 5, "end_module": 8},
    {"name": "BigData", "year": 2, "start_module": 5, "end_module": 6},
    {"name": "Введение в MLOps", "year": 2, "start_module": 5, "end_module": 5},
    {"name": "Генеративные модели", "year": 2, "start_module": 5, "end_module": 6},
    {"name": "Дополнительные главы ML", "year": 2, "start_module": 5, "end_module": 5},
    {"name": "ML System Design", "year": 2, "start_module": 5, "end_module": 5},
    {"name": "NLP - 1", "year": 2, "start_module": 5, "end_module": 5},
    {"name": "Введение в DE", "year": 2, "start_module": 6, "end_module": 6},
    {"name": "Векторный поиск", "year": 2, "start_module": 6, "end_module": 6},
    {"name": "DL для звука", "year": 2, "start_module": 6, "end_module": 7},
    {"name": "Интеллектуальный акустический мониторинг", "year": 2, "start_module": 6, "end_module": 6},
    {"name": "MLOps", "year": 2, "start_module": 6, "end_module": 6},
    {"name": "Мультимодальные нейросети", "year": 2, "start_module": 6, "end_module": 6},
    {"name": "NLP - 2", "year": 2, "start_module": 6, "end_module": 6},
    {"name": "Al Case Study (LLM Project)", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "ГО на графах", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Компьютерное зрение", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "НИС «Современное Машинное Обучение»", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Обучение с подкреплением", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Подготовка к собеседованиям", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Распределенные системы", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Факультатив BigData", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Факультатив LLM", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Валидация ИИ моделей", "year": 2, "start_module": 7, "end_module": 7},
    {"name": "Факультатив 3D CV", "year": 2, "start_module": 8, "end_module": 8}
]